---
title: SAE部署Django1.7失败问题
layout: blog
categories: blog
tags: python django
blogId: 18
---
{% capture media_path %}{{site.media}}/blog/{{page.blogId}}{% endcapture %}

在SAE上刚更新了Django1.7版本，结果本地能跑，到服务器就出了问题了。

> Check that you don't make non-lazy gettext calls at import time

解决方法：修改index.wsgi

原来是：（1.6之前的写法导致的）

<pre class="brush:python;toolbar:false">from django.core.handlers.wsgi import WSGIHandler
import sae
import os

application = sae.create_wsgi_app(WSGIHandler())</pre>

修改后：

<pre class="brush:python;toolbar:false">from django.core.wsgi import get_wsgi_application
import sae
import os

application = sae.create_wsgi_app(get_wsgi_application())</pre>

仅仅是简单的记录![](http://img.baidu.com/hi/jx2/j_0059.gif)